[build]
command = "hugo --gc --minify -b $URL"
publish = "public"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV           = "production"
HUGO_VERSION       = "0.111.1"
NODE_VERSION       = "v18.12.1"
NPM_VERSION        = "8.19.2"

[context.deploy-preview]
command = "./build.sh && hugo --gc --minify --buildFuture --buildDrafts -b $DEPLOY_PRIME_URL "

[context.deploy-preview.environment]
HUGO_VERSION       = "0.111.1"
NODE_VERSION       = "v18.12.1"
NPM_VERSION        = "8.19.2"

[context.branch-deploy]
command = "./build.sh && hugo --gc --minify --buildFuture --buildDrafts -b $DEPLOY_PRIME_URL "

[context.branch-deploy.environment]
HUGO_VERSION       = "0.111.1"
NODE_VERSION       = "v18.12.1"
NPM_VERSION        = "8.19.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
